version: '3.6'

services:
  tiny-monitor-api:
    image: tiny-monitor-api
    container_name: ${CONTAINER_NAME}
    build: .
    restart: unless-stopped
    ports:
      - target: 80
        published: ${API_PORT}
        mode: host
        protocol: tcp
    networks: 
      - tiny-monitor-net
    environment:
      SUPERVISOR_APIKEY: ${SUPERVISOR_APIKEY}

networks:
  tiny-monitor-net:
    name: tiny-monitor-net
